name: simple_schedule
description: 简课表 - 跨平台课程表管理应用
publish_to: 'none'
version: 2.5.0+22

environment:
  sdk: '>=3.11.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  sqflite: ^2.3.0
  path: ^1.8.3
  shared_preferences: ^2.2.2
  uuid: ^4.2.1
  intl: ^0.19.0
  flutter_colorpicker: ^1.0.3
  path_provider: ^2.1.1
  excel: ^4.0.6
  file_picker: ^8.0.0
  home_widget: 0.7.0
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.0
  package_info_plus: ^8.0.2
  google_fonts: ^6.2.1
  sqflite_common_ffi: ^2.4.0+3
  http: ^1.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  fonts:
    - family: NotoSerifSC
      fonts:
        - asset: assets/fonts/NotoSerifSC-VF.ttf
    - family: Newsreader
      fonts:
        - asset: assets/fonts/Newsreader.ttf
    - family: LXGWWenKai
      fonts:
        - asset: assets/fonts/LXGWWenKaiLite-Regular.ttf
